# Generated by Django 4.1 on 2023-06-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qw_value', models.CharField(max_length=200)),
                ('ws_value', models.CharField(max_length=200)),
                ('jbfy_value', models.CharField(max_length=200)),
                ('xzqh_p_value', models.CharField(max_length=200)),
                ('xzqh_c_value', models.CharField(max_length=200)),
                ('land_value', models.CharField(max_length=200)),
            ],
        ),
    ]
