# Generated by Django 4.2.1 on 2023-06-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
