# Generated by Django 4.2.1 on 2023-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='qw_value',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
