# Generated by Django 4.2.1 on 2023-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0002_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qw_value', models.TextField(max_length=500)),
                ('head', models.CharField(max_length=200)),
                ('related_people', models.TextField()),
                ('judicial_record', models.TextField()),
                ('basic_info', models.TextField()),
                ('judgement_process', models.TextField()),
                ('result', models.TextField()),
                ('tail', models.TextField()),
                ('note_name', models.CharField(max_length=30)),
                ('judge_prop', models.CharField(max_length=30)),
                ('court', models.CharField(max_length=30)),
                ('case_reason', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2023)),
                ('laws', models.ManyToManyField(related_name='cases', to='case.law')),
            ],
        ),
    ]
